"""initial audit ledger

Hand-written rather than autogenerated: this is the schema the ledger is
defined by, and it should read as a decision rather than as a diff.

Revision ID: 0001_initial_audit_ledger
Revises:
Create Date: 2026-09-22
"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = "0001_initial_audit_ledger"
down_revision = None
branch_labels = None
depends_on = None

# Postgres stores `json` as text and reparses on every read; `jsonb` is binary
# and indexable. Spelled out here rather than imported from app code, so the
# migration keeps describing this schema even when the models move on.
JSON_VARIANT = sa.JSON().with_variant(postgresql.JSONB, "postgresql")


def upgrade() -> None:
    op.create_table(
        "screening_receipts",
        sa.Column("id", sa.Uuid(), nullable=False),
        # Frappe's identifiers. Foreign to this database by design: the engine
        # does not own applicants and must not assume they still exist, so
        # there is no foreign key to add here, ever.
        sa.Column("applicant_id", sa.String(length=140), nullable=False),
        sa.Column("job_opening_id", sa.String(length=140), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column("original_filename", sa.String(length=512), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_screening_receipts_applicant_id"),
        "screening_receipts",
        ["applicant_id"],
    )
    op.create_index(
        op.f("ix_screening_receipts_job_opening_id"),
        "screening_receipts",
        ["job_opening_id"],
    )
    op.create_index(
        op.f("ix_screening_receipts_status"), "screening_receipts", ["status"]
    )

    op.create_table(
        "scorecard_audits",
        sa.Column("id", sa.Uuid(), nullable=False),
        # RESTRICT, not CASCADE: deleting a receipt must not quietly erase the
        # record of a hiring decision that was made from it.
        sa.Column("receipt_id", sa.Uuid(), nullable=False),
        sa.Column("applicant_id", sa.String(length=140), nullable=False),
        sa.Column("job_opening_id", sa.String(length=140), nullable=False),
        sa.Column("model_id", sa.String(length=128), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("criteria_version", sa.Integer(), nullable=False),
        sa.Column("eligibility_outcome", sa.String(length=16), nullable=False),
        sa.Column("rule_results", JSON_VARIANT, nullable=False),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("recommendation", sa.String(length=32), nullable=True),
        sa.Column("payload", JSON_VARIANT, nullable=False),
        sa.Column("scoring_profile", JSON_VARIANT, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["receipt_id"], ["screening_receipts.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scorecard_audits_receipt_id"), "scorecard_audits", ["receipt_id"]
    )
    op.create_index(
        op.f("ix_scorecard_audits_applicant_id"), "scorecard_audits", ["applicant_id"]
    )
    op.create_index(
        op.f("ix_scorecard_audits_job_opening_id"),
        "scorecard_audits",
        ["job_opening_id"],
    )
    op.create_index(
        op.f("ix_scorecard_audits_eligibility_outcome"),
        "scorecard_audits",
        ["eligibility_outcome"],
    )
    op.create_index(
        op.f("ix_scorecard_audits_recommendation"),
        "scorecard_audits",
        ["recommendation"],
    )


def downgrade() -> None:
    op.drop_table("scorecard_audits")
    op.drop_table("screening_receipts")
